# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottieTest
    pod 'lottie-ios'

  target 'LottieTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieTestUITests' do
    # Pods for testing
  end

end
