# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseStorage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseStorage
	pod 'Firebase/Analytics'
	pod 'Firebase/Storage'

  target 'FirebaseStorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseStorageUITests' do
    # Pods for testing
  end

end
